### PR TITLE
Fix the default solution project name and add a few missing files

### PR DESCRIPTION
**Pull request by 0xC0000054**

### CODE REVIEW

**Comment by Squall-Leonhart** [comment]
This produces a working build, the 0.1.0 release does not work for some reason for myself (no log created, no change to the fps decrease during simulation)

**Comment by 0xC0000054** [comment]
> This produces a working build, the 0.1.0 release does not work for some reason for myself (no log created, no change to the fps decrease during simulation)

The 0.1.0 release was compiled as a debug build.  This causes it to link to the debug version of the MSVC 2022 runtime, which is only available if you have Visual Studio 2022 installed. Microsoft doesn't license those runtime DLLs for redistribution.

**Comment by Squall-Leonhart** [comment]
Which i obviously have installed by being able to build it :p

Hrm, tried it on another system without VS installed, and it doesn't even throw the usual msvcp140p.dll not found warning.

**Comment by caspervg** [comment]
> This produces a working build, the 0.1.0 release does not work for some reason for myself (no log created, no change to the fps decrease during simulation)

@Squall-Leonhart I've just released v0.1.1 which should be a release build. https://github.com/caspervg/sc4-disable-fps-limits/releases/tag/v0.1.1 Can you check if that one works for you?

**Pull request merged**
